Fixed NoClassDefFoundError caused by changes to the addon version compatibility algorithm Fixes https://github.com/BentoBoxWorld/BentoBox/issues/1177. It was introduced in https://github.com/BentoBoxWorld/BentoBox/commit/332967950f8f5ec1cf4350f5df78250b82083c6a.